The deal down shuffle is a methematical way to shuffle a packet of card.
The steps to perform this is:
1. place top card down in a separate pile
2. place next card on the bottom of the dealing packet
3. place the next card on top of the separate pile
4. repeat until no cards are left in the hand.

In [1]:
import numpy as np

def T(x):
  '''
  [1,2,3,4] -> [4,2,3,1]
  [1,2,3,4,5] -> [2,4,5,3,1]
  [1,2,3,4,5,6] -> [4,6,2,5,3,1]
  '''
  if x == []:
    return "bad array"
  elif len(x) == 1:
    return x
  else:
    y = [x.pop(0)]
    x.append(x.pop(0))
    return T(x) + y

In [ ]:
from math import log, floor, ceil
def alpha(N,x):
  # N = number of cards
  # x = old position
  # return power constant for calculation
  # this is an approximation
  A = log(N,2) - log(2*x-1,2) - 0.5
  if abs(floor(A)-A) <= 0.5:
    return floor(A)
  else:
    return ceil(A)

 # return (log(N,2) - log(2*x-1,2) - 0.5)

In [ ]:
def N(n,x):
  # n = number of cards
  # x = old position
  # return new position
  a = alpha(n,x)
  print((2*x-1)*pow(2,a))
  print(a)
  if n > (2*x-1)*pow(2,a):
    return int(2*(n-(2*x-1)*pow(2,a)))
  elif n <= (2*x-1)*pow(2,a):
    return int(2*n-(2*x-1))
  else:
    print("Error")

In [ ]:
n = 21
z = list(range(1,n+1))
TT = T(z)

NN = []
for i in range(1,n+1):
  NN.append(N(n,i))
print(NN)
TT

[10, 18, 2, 14, 6, 20, 16, 12, 8, 4, 21, 19, 17, 15, 13, 11, 9, 7, 5, 3, 1]


[10, 18, 2, 14, 6, 20, 16, 12, 8, 4, 21, 19, 17, 15, 13, 11, 9, 7, 5, 3, 1]

Above is an examples of the functions. N(n,x) finds the new position of T(x). 
The output compares how N does compared to the answer T.
There are still issues in the math, sometimes the prediction is wrong, but for the most part, N is usually correct. 

In [32]:
def num_to_reset(N, max_iter = 100):
  #returns the number of deals needed to reset
  start = list(range(1,N+1))
  looping = list(range(1,N+1))
  iter = 0
  for i in range(max_iter):
    looping = T(looping)
    iter += 1
    if looping == start:
      return iter

  return iter

Conjecture: binary numbers take the least number of shuffles to reset.

1,2,2,4,4,12,12,24,24

In [ ]:
print(num_to_reset(16),"loops to to reset")

x = list(range(1,16+1))
for i in range(5):
  print(i,x)
  x = T(x)

4 loops to to reset
0 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
1 [16, 8, 12, 4, 14, 10, 6, 2, 15, 13, 11, 9, 7, 5, 3, 1]
2 [1, 2, 9, 4, 5, 13, 10, 8, 3, 7, 11, 15, 6, 14, 12, 16]
3 [16, 8, 15, 4, 14, 7, 13, 2, 12, 6, 11, 3, 10, 5, 9, 1]
4 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]


finding when the number of cards in a packet == number of iterations to reset

In [ ]:
n_cycle = []
ugly_cycle = []
for n in range(1,100+1):
  if n == num_to_reset(n):
    n_cycle.append(n)
  if n < num_to_reset(n):
    ugly_cycle.append(n)
print("n-cycles",n_cycle)
print("ugly cycles",ugly_cycle)

n-cycles [1, 2, 3, 5, 6, 12, 15, 17, 18, 20, 21, 26, 27, 33, 35, 41, 42, 45, 48, 50, 53, 57, 60, 66, 68, 78, 87, 90, 92, 95, 96, 100]
ugly cycles [11, 14, 23, 24, 25, 29, 31, 34, 37, 38, 39, 43, 47, 49, 52, 54, 55, 56, 58, 59, 61, 62, 63, 65, 67, 69, 70, 71, 72, 73, 74, 77, 80, 81, 82, 83, 84, 85, 86, 88, 89, 91, 97, 98, 99]


In [82]:
n = 10
get_subcycles(n)
def get_subcycles(n):
  # n = length of list
  # m = num of iter to repeat
  m = num_to_reset(n)

  history = np.zeros([m,n],dtype = int) #storing past positions
  a = list(range(1,n+1))
  history[0] = a
  for i in range(1,m):
    x[i] = T(list(history[i-1]))
  print(history)
  print(history.T)



6
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 4  8 10  6  2  9  7  5  3  1]
 [ 6  5  1  9  8  3  7  2 10  4]
 [ 9  2  4  3  5 10  7  8  1  6]
 [ 3  8  6 10  2  1  7  5  4  9]
 [10  5  9  1  8  4  7  2  6  3]]
[[ 1  4  6  9  3 10]
 [ 2  8  5  2  8  5]
 [ 3 10  1  4  6  9]
 [ 4  6  9  3 10  1]
 [ 5  2  8  5  2  8]
 [ 6  9  3 10  1  4]
 [ 7  7  7  7  7  7]
 [ 8  5  2  8  5  2]
 [ 9  3 10  1  4  6]
 [10  1  4  6  9  3]]


In [94]:
y = []
for i in range(n):
  y.append(list(set(sorted(x.T[i]))))
for j in range(n):
  print(y[j])
uniq_animal_groups = map(y)
print(uniq_animal_groups)

[1, 3, 4, 6, 9, 10]
[8, 2, 5]
[1, 3, 4, 6, 9, 10]
[1, 3, 4, 6, 9, 10]
[8, 2, 5]
[1, 3, 4, 6, 9, 10]
[7]
[8, 2, 5]
[1, 3, 4, 6, 9, 10]
[1, 3, 4, 6, 9, 10]


TypeError: ignored